export const profiles = [
  {
    id: "1",
    img: "/images/bouw1.jpg",
    name: "Mariah Carey",
    price: "€172 per dag",
    worktime: "77 weken",
    occupation: "Bouwvakker",
  },
  {
    id: "2",
    img: "/images/bouw2.jpg",
    name: "Giovanni",
    price: "€167 per dag",
    worktime: "75 weken",
    occupation: "Bouwvakker",
  },
  {
    id: "3",
    img: "/images/bouw3.jpg",
    name: "Fabio",
    price: "€196 per dag",
    worktime: "32 weken",
    occupation: "Bouwvakker",
  },
  ,
  {
    id: "4",
    img: "/images/elek1.jpg",
    name: "Delilah",
    price: "€172 per dag",
    worktime: "37 weken",
    occupation: "Elektricien",
  },
  {
    id: "5",
    img: "/images/elek2.jpg",
    name: "Design Team",
    price: "€167 per dag",
    worktime: "75 weken",
    occupation: "Elektricien",
  },
  {
    id: "6",
    img: "/images/elek3.jpg",
    name: "Palpatine Electric",
    price: "€500 per dag",
    worktime: "∞",
    occupation: "Elektricien",
  },
  {
    id: "7",
    img: "/images/schilder1.jpg",
    name: "Amidala",
    price: "€50 per dag",
    worktime: "40 weken",
    occupation: "Schilder",
  },
  {
    id: "8",
    img: "/images/schilder2.jpg",
    name: "C-3PaintO",
    price: "€143 per dag",
    worktime: "75 weken",
    occupation: "Schilder",
  },
  {
    id: "9",
    img: "/images/schilder3.jpg",
    name: "Maria",
    price: "€250 per dag",
    worktime: "100 weken",
    occupation: "Schilder",
  },
  {
    id: "10",
    img: "/images/verhuis3.jpg",
    name: "Rey Skywalker",
    price: "€122 per dag",
    worktime: "60 weken",
    occupation: "Verhuizer",
  },
  {
    id: "11",
    img: "/images/verhuis1.jpg",
    name: "Han Solo",
    price: "€200 per dag",
    worktime: "80 weken",
    occupation: "Verhuizer",
  },
  {
    id: "12",
    img: "/images/verhuis2.jpg",
    name: "Galactic Empire",
    price: "€499 per dag",
    worktime: "320 weken",
    occupation: "Verhuizer",
  },
  {
    id: "13",
    img: "/images/tuin1.jpg",
    name: "Marie Curie",
    price: "€172 per dag",
    worktime: "44 weken",
    occupation: "Tuinier",
  },
  {
    id: "14",
    img: "/images/tuin2.jpg",
    name: "R2-D2",
    price: "€200 per dag",
    worktime: "65 weken",
    occupation: "Tuinier",
  },
  {
    id: "15",
    img: "/images/tuin3.jpg",
    name: "Gaia",
    price: "€96 per dag",
    worktime: "32 weken",
    occupation: "Tuinier",
  },
];
