export const profiles = [
  {
    id: "1",
    img: "/images/bouw1.jpg",
    name: "Marie Karie",
    email: "marie-karie",
    price: "€172 per dag",
    worktime: "77 weken",
    location: "Sint-Martens-Latem",
    occupation: "bouwvakker",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
  {
    id: "2",
    img: "/images/bouw2.jpg",
    name: "Giovanni",
    email: "giovanni",
    price: "€167 per dag",
    worktime: "75 weken",
    location: "Spa",
    occupation: "bouwvakker",
    captionOne: " is een ",
    captionTwo: "Hij runt zijn business vanuit ",
  },
  {
    id: "3",
    img: "/images/bouw3.jpg",
    name: "Fabio Boticelli",
    email: "fabio-boticelli",
    price: "€196 per dag",
    worktime: "32 weken",
    location: "Drongen",
    occupation: "bouwvakker",
    captionOne: " is een ",
    captionTwo: "Hij runt zijn business vanuit ",
  },
  ,
  {
    id: "4",
    img: "/images/elek1.jpg",
    name: "Delilah Vanrieten",
    email: "delilah-vanrieten",
    price: "€172 per dag",
    worktime: "37 weken",
    location: "Nieuwpoort",
    occupation: "elektricien",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
  {
    id: "5",
    img: "/images/elek2.jpg",
    name: "Design Team",
    email: "design-team",
    price: "€167 per dag",
    worktime: "75 weken",
    location: "Kortrijk",
    occupation: "elektricien",
    captionOne: " is een ",
    captionTwo: "Ze runnen de business vanuit ",
  },
  {
    id: "6",
    img: "/images/elek3.jpg",
    name: "Palpatine Electric",
    email: "palpatine-electric",
    price: "€500 per dag",
    worktime: "∞",
    location: "Langenakker",
    occupation: "elektricien",
    captionOne: " is een ",
    captionTwo: "Hij runt zijn business vanuit ",
  },
  {
    id: "7",
    img: "/images/schilder1.jpg",
    name: "Fien Baekermann",
    email: "fien-baekermann",
    price: "€50 per dag",
    worktime: "40 weken",
    location: "Diest",
    occupation: "schilder",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
  {
    id: "8",
    img: "/images/schilder2.jpg",
    name: "Schilderwerken Corneels",
    email: "schilderwerken-corneels",
    price: "€143 per dag",
    worktime: "75 weken",
    location: "Oostkamp",
    occupation: "schilder",
    captionOne: " is een ",
    captionTwo: "De business wordt gerund vanuit ",
  },
  {
    id: "9",
    img: "/images/schilder3.jpg",
    name: "Mara De Tobbe",
    email: "mara-de-tobbe",
    price: "€250 per dag",
    worktime: "100 weken",
    location: "Luik",
    occupation: "schilder",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
  {
    id: "10",
    img: "/images/verhuis3.jpg",
    name: "Lieslot Kasteels",
    email: "lieselot-kasteels",
    price: "€122 per dag",
    worktime: "60 weken",
    location: "Antwerpen",
    occupation: "verhuizer",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
  {
    id: "11",
    img: "/images/verhuis1.jpg",
    name: "Han Solo",
    email: "han-solo",
    price: "€200 per dag",
    worktime: "80 weken",
    location: "Mol",
    occupation: "verhuizer",
    captionOne: " is een ",
    captionTwo: "Hij runt zijn business vanuit ",
  },
  {
    id: "12",
    img: "/images/verhuis2.jpg",
    name: "Vanavenende Verhuis",
    email: "vanavenende-verhuis",
    price: "€499 per dag",
    worktime: "320 weken",
    location: "Oostrozenbeek",
    occupation: "verhuizer",
    captionOne: " is een ",
    captionTwo: "De business wordt gerund vanuit ",
  },
  {
    id: "13",
    img: "/images/tuin1.jpg",
    name: "Karobo Diamini",
    email: "karobo-diamini",
    price: "€172 per dag",
    worktime: "44 weken",
    location: "Gent",
    occupation: "tuinier",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
  {
    id: "14",
    img: "/images/tuin2.jpg",
    name: "Piet Steels",
    email: "piet-steels",
    price: "€200 per dag",
    worktime: "65 weken",
    location: "Ternat",
    occupation: "tuinier",
    captionOne: " is een ",
    captionTwo: "De business wordt gerund vanuit ",
  },
  {
    id: "15",
    img: "/images/tuin3.jpg",
    name: "Gaia Vermeylen",
    email: "gaia-vermeylen",
    price: "€96 per dag",
    worktime: "32 weken",
    location: "Dendermonde",
    occupation: "tuinier",
    captionOne: " is een ",
    captionTwo: "Ze runt haar business vanuit ",
  },
];
