export const profiles = [
  {
    id: "3",
    img: "/bouw1.jpg",
    name: "Mariah Carey",
    price: "172 euro per dag",
    worktime: "77 weken",
    occupation: "Bouwvakker",
  },
  {
    id: "4",
    img: "/bouw2.jpg",
    name: "Giovanni (van Pokémon)",
    price: "167 euro per dag",
    worktime: "75 weken",
    occupation: "Bouwvakker",
  },
  {
    id: "5",
    img: "/bouw3.jpg",
    name: "Fabio",
    price: "196 euro per dag",
    worktime: "32 weken",
    occupation: "Bouwvakker",
  },
  ,
  {
    id: "6",
    img: "/elek1.jpg",
    name: "Delilah",
    price: "172 euro per dag",
    worktime: "37 weken",
    occupation: "Elektricien",
  },
  {
    id: "7",
    img: "/elek2.jpg",
    name: "Design Team",
    price: "167 euro per dag",
    worktime: "75 weken",
    occupation: "Elektricien",
  },
  {
    id: "8",
    img: "/elek3.jpg",
    name: "Palpatine Electric",
    price: "500 euro per dag",
    worktime: "∞",
    occupation: "Elektricien",
  },
  {
    id: "9",
    img: "/schilder1.jpg",
    name: "Amidala",
    price: "50 euro per dag",
    worktime: "40 weken",
    occupation: "Schilder",
  },
  {
    id: "10",
    img: "/schilder2.jpg",
    name: "C-3PaintO",
    price: "143 euro per dag",
    worktime: "75 weken",
    occupation: "Schilder",
  },
  {
    id: "11",
    img: "/schilder3.jpg",
    name: "Maria",
    price: "250 euro per dag",
    worktime: "100 weken",
    occupation: "Schilder",
  },
  {
    id: "1",
    img: "/verhuis3.jpg",
    name: "Rey Skywalker",
    price: "122 euro per dag",
    worktime: "60 weken",
    occupation: "Verhuizer",
  },
  {
    id: "2",
    img: "/verhuis1.jpg",
    name: "Han Solo",
    price: "200 euro per dag",
    worktime: "80 weken",
    occupation: "Verhuizer",
  },
  {
    id: "3",
    img: "/verhuis2.jpg",
    name: "Galactic Empire",
    price: "499 euro per dag",
    worktime: "320 weken",
    occupation: "Verhuizer",
  },
  {
    id: "12",
    img: "/tuin1.jpg",
    name: "Marie Curie",
    price: "172 euro per dag",
    worktime: "44 weken",
    occupation: "Tuinier",
  },
  {
    id: "13",
    img: "/tuin2.jpg",
    name: "R2-D2",
    price: "200 euro per dag",
    worktime: "65 weken",
    occupation: "Tuinier",
  },
  {
    id: "14",
    img: "/tuin3.jpg",
    name: "Gaia",
    price: "96 euro per dag",
    worktime: "32 weken",
    occupation: "Tuinier",
  },
];
